- R/chrome.R
if `google-chrome` is not found on linux, try `chromium-browser`, which is the apt-available alternative (on Ubuntu 18.04), and is the binary installed by `yum install chromium` on Centos7 as well. This is helpful for e.g. RStudio Server Pro
Ultimately, the error message here was not helpful: 
```
ChromoteSession$new()
#> Error: <c_error in rethrow_call(c_processx_exec, command, c(command, args), stdin,  ...:
cannot start processx process '' (system error 2, No such file or directory) @unix/processx.c:584 (processx_exec)>
```
A pointer to the `CHROMOTE_CHROME` environment variable (and perhaps a clear error) would be desirable here. This approach is pretty naive, so definitely no hard feelings if you want to implement differently!
> add a check for chromium-browser

- DESCRIPTION
- R/chromote.R
This uses the threaded version of websocket and the version of later which auto-runs child event loops. This reduces the idle CPU usage of Chromote from 6% to 0% on my computer.
This should be merged after https://github.com/r-lib/later/pull/119.
> Use updated version of later and websocket with auto-running child event loop

- R/chrome.R
On Ubuntu 20.04, `chromium` is installed in `/snap/bin/chromium`.  
`find_chrome()` does not find it unless it also looks up `"chromium"`.
> Search for "chromium" path on Linux

- R/chromote_session.R
- man/ChromoteSession.Rd
Closes #40.
Please note that I haven't really tested this. I am not 100% sure that this will work correctly, if, for example, a ChromoteSession has `auto_events=FALSE` while the parent Chromote has `auto_events=TRUE` (or vice versa). Similarly, I'm not 100% it will work correctly if two ChromoteSessions have different `auto_events` settings.
@RLesur if you could test this out, I would appreciate it.
> Add auto_events to ChromoteSession

- R/chromote.R
- R/chromote_session.R
The aim of this PR is to fix #44 (regression introduced by #42).
The `Inspector` domain is only available to the ChromoteSession and not Chromote. So, this PR moves the code introduced by #42 in the ChromoteSession.
> Inspector is not exposed by Chromote

- R/screenshot.R
Sometimes half a second is not enough of a delay for an app to equilibrate after a resize event. By adding a `delay` parameter the user can now make it longer if necessary.
> Add custom delay before taking screenshot

- R/chrome.R
- man/Chrome.Rd
- man/ChromoteSession.Rd
Adds a short bit of documentation about how to pass command-line arguments for Chromium startup. Without docs, it was a bit confusing to figure out the format for both binary on/off arguments and key-value arguments. 
Also in building the docs, the .rd for the screenshot function from #50 with its new delay argument was rebuilt.
> Startup args documentation

- DESCRIPTION
Especially given the pattern used by https://github.com/rstudio/r-system-requirements , I thought it would be good to highlight the `SystemRequirements` here.
> Add system requirements for chromium

- R/chromote.R
- R/chromote_session.R
Related: https://en.wikipedia.org/wiki/Graphics_display_resolution#WUXGA_(1920%C3%971200)
IDK why the screen is so small to begin with.
> Bump browser size to 1200 x 1600 (3:4 ratio)

- R/chromote.R
- R/chromote_session.R
- man/Chromote.Rd
- man/ChromoteSession.Rd
Keep 4:3 ratio.
Bootstrap uses a breakpoint of 992px for desktops: https://getbootstrap.com/docs/4.0/layout/overview/
> Use BootStrap responsive breakpoint of Large devices

- R/chromote.R
- R/chromote_session.R
- README.Rmd
- README.md
- man/Chromote.Rd
- man/ChromoteSession.Rd
Fixes #75
Changes
However...
`ChromoteSession` can not access the private events of `Chromote` or vice versa. `R6` objects do not inherit their `super`'s private methods.  This prevents moving many `self` helper methods to be `private` for both `Chromote` and `ChromoteSession` as they can not access each other's `private` methods. 
It _might_ be possible if R6 has access to `super_private` (or something similar), but it would not get rid of every method (`$mark_closed()`).
> Remove `ChromoteSession$get_parent()` and lock `$protocol`

- R/chrome.R
- R/utils.R
- tests/testthat/test-utils.R
This is an alternative fix to #99 and #100. I borrowed heavily from [httpuv::random_port()](https://github.com/rstudio/httpuv/blob/main/R/random_port.R) with a few big differences (since starting up chromote isn't quite as simple as starting up a short-lived http server) that I'll call out briefly.
* I've added `with_random_port()` that follows the logic of `random_port()` but accepts a `startup` function. This function should take `port` and `host` (although `host` defaults to `http://127.0.0.1`) and is called with a random port.
* The function either fails or returns a non-null value, in which case we assume we've successfully found an open port. There are four possible next steps for a failure:
1. For a generic error, if we haven't exhausted the `n` tries, we try `startup()` again with …
> Use a random port and set `--remote-allow-origins` to local host + port when launching chrome

- R/chrome.R
Adresses #108. Better message from `find_chrome` on Windows when Google Chrome is not found.
> Better message from `find_chrome` on Windows when Chrome not found.

- NEWS.md
- R/chrome.R
Fixes #89
Fixes #91
Closes #90
I refactored the checks a bit so that they share logic:
* `find_chrome_{windows,mac,linux}()` looks for the path in common places and returns any if found
* `inform_if_chrome_not_found()` returns the path if found or returns NULL with an informative message if it isn't found
> Check in more places for Chrome on Linux and Mac

- R/chrome.R
- man/find_chrome.Rd
Adds documentation to `find_chrome()`. In particular will help users discover the `CHROMOTE_CHROME` environment variable and better understand its limitations.
Fixes #108 (technically fixed by #117, but this also addresses a coment there)
> docs(find_chrome): Improve docs

- R/chromote.R
- R/chromote_session.R
- man/Chromote.Rd
- man/ChromoteSession.Rd
Fixes #112
The `\dontrun{}` examples don't look great on the website or in any of the manuals.
This PR moves them into an "Examples" section with some static R code. Their order in the docs move around slightly, but it's the closest we can get to what we want. In particular, it ensures consistent formatting everywhere docs are presented without causing the examples to be tested on CRAN
> docs: Make examples static

- NEWS.md
- R/chrome.R
- R/chromote.R
Fixes #22 
Adds a `chromote.timeout` option to control the timeout duration in the websocket and open port connection logic. These were both previously 10 seconds. For simplicity I opted for a single option which is currently undocumented other than in the NEWS item
> feat(chrome.timeout): Add an option for choosing timeout duration

- DESCRIPTION
- NEWS.md
- R/chromote_session.R
- R/screenshot.R
- man/ChromoteSession.Rd
For #96
This PR opens the door for users to set `captureBeyondViewport = FALSE` or the other [available `Page.captureScreenshot` options](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot).
I think in the long run we might want to apply the puppeteer approach, either in chromote or in the `get_screenshot()` method in shinytest2. This moves us in that direction while also unblocking our current testing needs.
Here's an example that could benefit from the new `options` argument. Note that we currently don't adjust the `format` so screenshots are always in `png` format (I'll do a separate PR to address that problem.)
``` r
library(chromote)
chrm <- ChromoteSession$new()
{
chrm$Page$navigate("https://posit.co")
chrm$Page$loadEventFired()
}
#> $timestamp
#> …
```
> feat(screenshot): Accept additional arguments that are passed to `Page.captureScreenshot()`

- NEWS.md
- R/chromote_session.R
- R/screenshot.R
- man/ChromoteSession.Rd
Follow up from #129 (will change base branch and rebase before merging).
This PR infers the screenshot format from the file extension, unless the user has explicitly set `options = list(format = "____")`.
This fixes an un-reported bug in `webshot2` where additional file types are supported by `webshot2::webshot()` but the actual file format is always `.png` even if `.jpg` was requested.
The format detection will throw an error for unknown file types; as mentioned above this can be circumvented by manully providing `format` in the `options` list.
``` r
pkgload::load_all("~/work/rstudio/chromote")
#> ℹ Loading chromote
chrm <- ChromoteSession$new()
{
chrm$Page$navigate("https://posit.co")
chrm$Page$loadEventFired()
}
#> $timestamp
#> [1] 149692.2
chrm$screenshot("posit.jpg")
#> [1] …
```
> feat(screenshot): Infer file format from `filename` extension

- NEWS.md
- R/chromote.R
- man/default_chrome_args.Rd
- tests/testthat/test-default_chromote_args.R
It is no longer needed as the underlying bugs have been fixed in chromium (for multiple years). This flag was dropped in puppeteer in https://github.com/puppeteer/puppeteer/pull/2908 and https://github.com/puppeteer/puppeteer/pull/4523.
> Drop the --disable-gpu flag

- DESCRIPTION
- NEWS.md
- R/browser.R
- R/chromote.R
- R/chromote_session.R
- man/Browser.Rd
- man/Chrome.Rd
- man/ChromeRemote.Rd
- man/Chromote.Rd
- man/ChromoteSession.Rd
When your computer goes to sleep, the websocket and all debugging sessions are closed. This PR ensures that Chromote and ChromoteSession report this accurately.
I distinguished between active and alive for Chromote but not ChromoteSession since the browser process continues to run in the background, even though we have lost our connection to it. There's no way to restore a closed debugging session. However, I'm not sure about the names; maybe I have alive and active around the wrong way?
Part of #94
---
I tested this code with:
```R
library(chromote)
sess <- ChromoteSession$new()
sess$is_active()
#> [1] TRUE
sess$parent$is_alive()
#> [1] TRUE
sess$is_active()
#> [1] FALSE
sess$parent$is_alive()
#> [1] FALSE
```
> Check that a chromote connection is alive

- R/chrome.R
When we fail to launch chrome, we print already out the contents of stderr in the error message. But there are often important details hidden in the stdout logs.
This PR adds the full path to the log file with the lines printed to stdout in the error message when chrome fails to launch.
Fixes #151
> feat: Include path to chrome log file in failed to connect message

- R/chromote.R
is_linux() is defined in utils.R, there is no need to re-define it in chromote.R
> Remove redundant function

- R/chrome.R
- R/utils.R
Two changes are required:
- Checking for the appropriate `sysname`
- Adding `chrome` to the list of searched executables, because that's the name of the main executable file, installed by the OpenBSD package.
> Adds support for chromote under OpenBSD

- DESCRIPTION
- NEWS.md
- R/chrome.R
- cran-comments.md
Fixes this :facepalm: :facepalm: :facepalm: of a bug I just introduced.
``` r
Sys.getenv("CHROMOTE_HEADLESS", NULL)
#> Error in Sys.getenv("CHROMOTE_HEADLESS", NULL): wrong type for argument
```
> hot-fix: v0.3.1

- DESCRIPTION
- NEWS.md
- R/chrome.R
Fixes #187
We now default to `--headless` and pass whatever value is given in `chromote.headless` or `CHROMOTE_HEADLESS` along directly to Chrome, relying on Chrome to fail for invalid headless values (if it fails at all).
> fix: Chrome no longer supports old headless mode

- NEWS.md
- R/chrome.R
Fixes #134
Sets `--crash-dumps-dir` for each session and uses `tempfile()` to create a consistent path name for a given session. (Previously, stdout and stderr would be written to log files with different "hashes".)
```r
options(chromote.launch.echo_cmd = TRUE)
b <- ChromoteSession$new()
#> Running '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' \
#>   --headless '--remote-debugging-port=23311' \
#>   '--remote-allow-origins=http://127.0.0.1:23311' \
#>   '--crash-dumps-dir=/var/folders/yl/0xhq7c7n3z7_9hp1356kctbr0000gp/T//RtmpcsWZVF/chrome-bd71710535fb-crashpad' \
#>   '--force-color-profile=srgb' --disable-extensions --mute-audio
```
With this change, we now use the same tempdir prefix for all three session-specific files/directories:
* …
> feat: Set a user-specific crash dump directory

- R/chromote.R
- R/manage.R
- man/chrome_versions.Rd
- man/with_chrome_version.Rd
Fixes #201
Adds support for new version identifiers: `latest-stable`, `latest-extended`, `latest-beta`, `latest-canary`, `latest-dev`.
The default for `with_chrome_version()` is now `latest-stable`, which will ensure that using managed versions gets an up-to-date, but not overly bleeding edge, version of Chrome.
```r
library(chromote)
with_chrome_version("latest-stable", {
b <- ChromoteSession$new()
writeLines(readLines(b$parent$url("/json")))
})
with_chrome_version("latest-canary", {
b <- ChromoteSession$new()
writeLines(readLines(b$parent$url("/json")))
})
```
> feat: Add support for `version="latest-stable"` and make it the new default

- DESCRIPTION
- NEWS.md
- R/chromote-package.R
- R/chromote_session.R
- R/import-standalone-obj-type.R
- R/import-standalone-types-check.R
- man/ChromoteSession.Rd
Adds `mobile` and `new_window` arguments to `ChromoteSession$new()` and updates the session initialization to use `Emulation.setDeviceMetricsOverride` instead of `Target.createTarget` to establish the dimensions of the new session.
See #204 for in-depth background.
> feat(ChromoteSession): width/height override device metrics, add `mobile` and `new_window` params

- NEWS.md
- R/chromote_session.R
- R/protocol.R
- README.Rmd
- README.md
- man/ChromoteSession.Rd
- tests/testthat/test-chromote_session.R
Adds helper methods to get and set the viewport size
``` r
pkgload::load_all("~/work/rstudio/chromote")
#> ℹ Loading chromote
page <- ChromoteSession$new(width = 400, height = 800, mobile = TRUE)
page$Page$navigate("https://example.com")
str(page$get_viewport_size())
#> List of 4
#>  $ width : int 400
#>  $ height: int 800
#>  $ zoom  : int 1
#>  $ mobile: logi TRUE
old <- page$set_viewport_size(
width = 500,
height = 800,
zoom = 2,
mobile = FALSE
)
str(old)
#> List of 4
#>  $ width : int 400
#>  $ height: int 800
#>  $ zoom  : int 1
#>  $ mobile: logi TRUE
str(page$get_viewport_size())
#> List of 4
#>  $ width : int 500
#>  $ height: int 800
#>  $ zoom  : num 2
#>  $ mobile: logi FALSE
```
> feat(ChromoteSession): Add `$set_viewport_size()` and `$get_viewport_size()` helper methods

- NEWS.md
- R/chrome.R
Avoids a bug like this:
``` r
output <- c(" ", " ", "\r\n")
output <- trimws(output)
output[nzchar(output)][[1]]
#> Error in output[nzchar(output)][[1]]: subscript out of bounds
```
> fix: Defend against empty output when checking Chrome version on Windows

- DESCRIPTION
- R/chromote.R
- R/chromote_session.R
- R/event_manager.R
- README.Rmd
- README.md
- man/Chromote.Rd
- man/ChromoteSession.Rd
- tests/testthat/_snaps/chromote_session.md
- tests/testthat/test-chromote_session.R
This is a completely different approach to solving #144 and replaces #207.
Rather than trying to track manual `$enable()` and `$disable()` calls, which we've found to be quite tricky to get right, the approach taken in this PR is to store arguments that should be used for the automatic `$enable()` events, leaving the entire auto-events lifecycle alone.
The pattern in #144 looks like this:
```r
chrome <- Chromote$new()
chrome$debug_messages(TRUE)
session <- ChromoteSession$new(parent = chrome)
#> [...clipped...]
session$Fetch$enable(
patterns = list(
list(urlPattern = "*")
),
handleAuthRequests = TRUE
)
#> SEND {"method":"Fetch.enable","params":{"patterns":[{"urlPattern":"*"}],"handleAuthRequests":true},"id":5,"sessionId":"C4B51F2AE8CF5BFF9CD8A33D82B83D3A"}
#> RECV …
```
> feat: `auto_events_enable_args` for ChromoteSession and Chromote

- R/chromote_session.R
- R/protocol.R
- R/screenshot.R
- tests/testthat/_snaps/chromote_session.md
- tests/testthat/test-chromote_session.R
Fixes rstudio/shinytest2#404
In rstudio/shinytest2#350, we went from using `deviceScaleFactor = 1` before screenshots to using `deviceScaleFactor = 0` in the `Emulation.setDeviceMetricsOverride` command. As pointed out there, the [CDP docs explain](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride) that this is equivalent to disabling deivce scaling.
The issue rstudio/shinytest2#350 resolved was a problem that was flagged for us on CRAN that was difficult to reproduce. IIRC, we eventually realized that we were getting different screenshot sizes on Mac when the Chrome browser window was being displayed on a Retina display vs a monitor (and by association, the failing manual CRAN tests were happening on a laptop display).
That said, playwright …
> fix: `deviceScaleFactor = 0` disables the metric override

- NEWS.md
- R/utils.R
Fixes #213
When we detect that the browser is a version of `chrome-headless-shell`, we no longer use the browser attached to chromote for `$view()` and instead use the default browser, i.e. `browseURL()` without overriding `browser`.
We use `$Browser$getVersion()` and look specifically for `HeadlessChrome` in the `product` name. (We _could_ also look at the browser path and look for `chrome-headless-shell`, but the path could be anything.)
``` r
library(chromote) # rstudio/chromote
local_chrome_version(binary = "chrome-headless-shell")
#> chromote will now use version 134.0.6998.88 of `chrome-headless-shell` for
#> mac-arm64.
b <- ChromoteSession$new()
b$Page$navigate("https://posit.co")
#> $frameId
#> [1] "6185CAE4361D8ED98E56723DCA4C4B7F"
#> 
#> $loaderId
#> [1] …
```
> fix(view): Use default browser when using `chrome-headless-shell`

- DESCRIPTION
- NEWS.md
- R/browser.R
- R/chrome.R
- R/chromote.R
- R/chromote_session.R
- R/manage.R
- R/screenshot.R
- man/Browser.Rd
- man/ChromeRemote.Rd
- man/Chromote.Rd
- tests/testthat.R
- tests/testthat/helper.R
- tests/testthat/setup.R
- tests/testthat/test-chrome.R
- tests/testthat/test-chromote_session.R
- tests/testthat/test-manage.R
- vignettes/example-remote-hosts.Rmd
One of the flaky tests was a timing issue that was easily resolved by following our own [best practices for loading pages](https://rstudio.github.io/chromote/articles/example-loading-pages.html).
The other flaky test revealed that the `$respawn()` changes missed a subtle consideration for how we manage connections to remote Chrome instances via `ChromeRemote`:
* `ChromeRemote` and `Chrome` inherit from `Browser`, which previously only considered the local process in the `$is_alive()` method. Now, `ChromeRemote` gains it's own `$is_alive()` method that checks if the remote instance is alive by reading the `/json/version` endpoint.
* `Chromote$close()` would attempt to shut down the remote browser, but unlike a normal `Chromote` instance, by definition chromote is not managing the browser …
> feat: Improve `$is_alive()`, `$close()` for local and remote processes

- NEWS.md
- R/chromote_session.R
- README.md
- man/ChromoteSession.Rd
- man/fragments/basic-usage.Rmd
- vignettes/commands-and-events.Rmd
- vignettes/example-authentication.Rmd
- vignettes/example-custom-headers.Rmd
- vignettes/example-custom-user-agent.Rmd
- vignettes/example-extract-text.Rmd
- vignettes/example-loading-page.Rmd
- vignettes/example-remote-hosts.Rmd
- vignettes/example-screenshot.Rmd
- vignettes/sync-async.Rmd
- vignettes/which-chrome.Rmd
Closes #177.
This adds a `$go_to()` method which creates the `loadEventFired` promise, then calls `navigate()`, then either returns the promise or waits for it, depending on the value of `wait_`.
With this method, we can simplify the docs and remove some of the caveats about it not always loading pages reliably.
If we want to take this, then we'll also need to update the docs and examples.
> Add `go_to()` method

- NEWS.md
- R/chromote_session.R
Fixes #224, stacks on #225
The `$view()` method now composes and tries the older `/devtools/inspector.html` path rather than using the fully-qualified chrome-devtools-frontend.appspot.com URL.
> fix(ChromoteSession): `$view()` tries old inspector path first
